#!/bin/bash

BINARY_LOCATION=$1
ISA=$2
N=$3
K=$4
ORIGINAL_MESSAGE=$5
ERROR_PATTERN=$6
CODE_TYPE=$7
POLICY=$8
TIEBREAK_POLICY=$9
CACHELINE=${10}
MESSAGE_BLOCKPOS=${11}
VERBOSE=${12}

# Library paths are for running on Hoffman2
LD_PRELOAD=$GCC5/lib64/libstdc++.so.6 LD_LIBRARY_PATH=$MATLAB/bin/glnxa64:$MATLAB/runtime/glnxa64:$LD_LIBRARY_PATH $BINARY_LOCATION/data_recovery $ISA $N $K $ORIGINAL_MESSAGE $ERROR_PATTERN $CODE_TYPE $POLICY $TIEBREAK_POLICY $CACHELINE $MESSAGE_BLOCKPOS $VERBOSE
