#!/bin/bash

ISA=$1
SPEC_BENCHMARK=$2
N=$3
K=$4
NUM_INST=$5
INPUT_DIRECTORY=$6
OUTPUT_DIRECTORY=$7

$INPUT_DIRECTORY/swd_ecc_inst_heuristic_recovery $ISA $SPEC_BENCHMARK $N $K $NUM_INST $INPUT_DIRECTORY $OUTPUT_DIRECTORY
