#!/bin/bash

BINARY_LOCATION=$1
ISA=$2
SPEC_BENCHMARK=$3
N=$4
K=$5
NUM_INST=$6
INPUT_FILE=$7
OUTPUT_FILE=$8
NUM_THREADS=$9

$BINARY_LOCATION/swd_ecc_inst_heuristic_recovery $ISA $SPEC_BENCHMARK $N $K $NUM_INST $INPUT_FILE $OUTPUT_FILE $NUM_THREADS
